/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as GuestIndexRouteImport } from './routes/_guest.index'
import { Route as ApiMetadataRouteImport } from './routes/api.metadata'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ProtectedWizardRouteImport } from './routes/_protected.wizard'
import { Route as ProtectedSignoutRouteImport } from './routes/_protected.signout'
import { Route as ProtectedProfileRouteImport } from './routes/_protected.profile'
import { Route as ProtectedPreviewRouteImport } from './routes/_protected.preview'
import { Route as ProtectedGalleryRouteImport } from './routes/_protected.gallery'
import { Route as ProtectedExampleRouteImport } from './routes/_protected.example'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedChatRouteImport } from './routes/_protected.chat'
import { Route as GuestSigninRouteImport } from './routes/_guest.signin'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected.profile.index'
import { Route as ApiTaskSubmitRouteImport } from './routes/api.task.submit'
import { Route as ApiTaskStatusRouteImport } from './routes/api.task.status'
import { Route as ApiTaskCancelRouteImport } from './routes/api.task.cancel'
import { Route as ApiModelsAihubmixRouteImport } from './routes/api.models.aihubmix'
import { Route as ApiMediaSplatRouteImport } from './routes/api.media.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ProtectedProfileMyProjectsRouteImport } from './routes/_protected.profile.my-projects'
import { Route as ProtectedProfileFavoritesProjectsRouteImport } from './routes/_protected.profile.favorites-projects'
import { Route as ProtectedProfileApiKeysRouteImport } from './routes/_protected.profile.api-keys'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const ApiMetadataRoute = ApiMetadataRouteImport.update({
  id: '/api/metadata',
  path: '/api/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWizardRoute = ProtectedWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSignoutRoute = ProtectedSignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPreviewRoute = ProtectedPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedGalleryRoute = ProtectedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExampleRoute = ProtectedExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatRoute = ProtectedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProtectedRoute,
} as any)
const GuestSigninRoute = GuestSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => GuestRoute,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedProfileRoute,
} as any)
const ApiTaskSubmitRoute = ApiTaskSubmitRouteImport.update({
  id: '/api/task/submit',
  path: '/api/task/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTaskStatusRoute = ApiTaskStatusRouteImport.update({
  id: '/api/task/status',
  path: '/api/task/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTaskCancelRoute = ApiTaskCancelRouteImport.update({
  id: '/api/task/cancel',
  path: '/api/task/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsAihubmixRoute = ApiModelsAihubmixRouteImport.update({
  id: '/api/models/aihubmix',
  path: '/api/models/aihubmix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileMyProjectsRoute =
  ProtectedProfileMyProjectsRouteImport.update({
    id: '/my-projects',
    path: '/my-projects',
    getParentRoute: () => ProtectedProfileRoute,
  } as any)
const ProtectedProfileFavoritesProjectsRoute =
  ProtectedProfileFavoritesProjectsRouteImport.update({
    id: '/favorites-projects',
    path: '/favorites-projects',
    getParentRoute: () => ProtectedProfileRoute,
  } as any)
const ProtectedProfileApiKeysRoute = ProtectedProfileApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProtectedProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GuestIndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/signin': typeof GuestSigninRoute
  '/chat': typeof ProtectedChatRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/example': typeof ProtectedExampleRoute
  '/gallery': typeof ProtectedGalleryRoute
  '/preview': typeof ProtectedPreviewRoute
  '/profile': typeof ProtectedProfileRouteWithChildren
  '/signout': typeof ProtectedSignoutRoute
  '/wizard': typeof ProtectedWizardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/metadata': typeof ApiMetadataRoute
  '/profile/api-keys': typeof ProtectedProfileApiKeysRoute
  '/profile/favorites-projects': typeof ProtectedProfileFavoritesProjectsRoute
  '/profile/my-projects': typeof ProtectedProfileMyProjectsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/models/aihubmix': typeof ApiModelsAihubmixRoute
  '/api/task/cancel': typeof ApiTaskCancelRoute
  '/api/task/status': typeof ApiTaskStatusRoute
  '/api/task/submit': typeof ApiTaskSubmitRoute
  '/profile/': typeof ProtectedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof GuestIndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/signin': typeof GuestSigninRoute
  '/chat': typeof ProtectedChatRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/example': typeof ProtectedExampleRoute
  '/gallery': typeof ProtectedGalleryRoute
  '/preview': typeof ProtectedPreviewRoute
  '/signout': typeof ProtectedSignoutRoute
  '/wizard': typeof ProtectedWizardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/metadata': typeof ApiMetadataRoute
  '/profile/api-keys': typeof ProtectedProfileApiKeysRoute
  '/profile/favorites-projects': typeof ProtectedProfileFavoritesProjectsRoute
  '/profile/my-projects': typeof ProtectedProfileMyProjectsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/models/aihubmix': typeof ApiModelsAihubmixRoute
  '/api/task/cancel': typeof ApiTaskCancelRoute
  '/api/task/status': typeof ApiTaskStatusRoute
  '/api/task/submit': typeof ApiTaskSubmitRoute
  '/profile': typeof ProtectedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guest': typeof GuestRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_guest/signin': typeof GuestSigninRoute
  '/_protected/chat': typeof ProtectedChatRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/example': typeof ProtectedExampleRoute
  '/_protected/gallery': typeof ProtectedGalleryRoute
  '/_protected/preview': typeof ProtectedPreviewRoute
  '/_protected/profile': typeof ProtectedProfileRouteWithChildren
  '/_protected/signout': typeof ProtectedSignoutRoute
  '/_protected/wizard': typeof ProtectedWizardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/metadata': typeof ApiMetadataRoute
  '/_guest/': typeof GuestIndexRoute
  '/_protected/profile/api-keys': typeof ProtectedProfileApiKeysRoute
  '/_protected/profile/favorites-projects': typeof ProtectedProfileFavoritesProjectsRoute
  '/_protected/profile/my-projects': typeof ProtectedProfileMyProjectsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/api/models/aihubmix': typeof ApiModelsAihubmixRoute
  '/api/task/cancel': typeof ApiTaskCancelRoute
  '/api/task/status': typeof ApiTaskStatusRoute
  '/api/task/submit': typeof ApiTaskSubmitRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/signin'
    | '/chat'
    | '/dashboard'
    | '/example'
    | '/gallery'
    | '/preview'
    | '/profile'
    | '/signout'
    | '/wizard'
    | '/api/chat'
    | '/api/metadata'
    | '/profile/api-keys'
    | '/profile/favorites-projects'
    | '/profile/my-projects'
    | '/api/auth/$'
    | '/api/media/$'
    | '/api/models/aihubmix'
    | '/api/task/cancel'
    | '/api/task/status'
    | '/api/task/submit'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/signin'
    | '/chat'
    | '/dashboard'
    | '/example'
    | '/gallery'
    | '/preview'
    | '/signout'
    | '/wizard'
    | '/api/chat'
    | '/api/metadata'
    | '/profile/api-keys'
    | '/profile/favorites-projects'
    | '/profile/my-projects'
    | '/api/auth/$'
    | '/api/media/$'
    | '/api/models/aihubmix'
    | '/api/task/cancel'
    | '/api/task/status'
    | '/api/task/submit'
    | '/profile'
  id:
    | '__root__'
    | '/_guest'
    | '/_protected'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/_guest/signin'
    | '/_protected/chat'
    | '/_protected/dashboard'
    | '/_protected/example'
    | '/_protected/gallery'
    | '/_protected/preview'
    | '/_protected/profile'
    | '/_protected/signout'
    | '/_protected/wizard'
    | '/api/chat'
    | '/api/metadata'
    | '/_guest/'
    | '/_protected/profile/api-keys'
    | '/_protected/profile/favorites-projects'
    | '/_protected/profile/my-projects'
    | '/api/auth/$'
    | '/api/media/$'
    | '/api/models/aihubmix'
    | '/api/task/cancel'
    | '/api/task/status'
    | '/api/task/submit'
    | '/_protected/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuestRoute: typeof GuestRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiMetadataRoute: typeof ApiMetadataRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  ApiModelsAihubmixRoute: typeof ApiModelsAihubmixRoute
  ApiTaskCancelRoute: typeof ApiTaskCancelRoute
  ApiTaskStatusRoute: typeof ApiTaskStatusRoute
  ApiTaskSubmitRoute: typeof ApiTaskSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/api/metadata': {
      id: '/api/metadata'
      path: '/api/metadata'
      fullPath: '/api/metadata'
      preLoaderRoute: typeof ApiMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/wizard': {
      id: '/_protected/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof ProtectedWizardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/signout': {
      id: '/_protected/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof ProtectedSignoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/preview': {
      id: '/_protected/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof ProtectedPreviewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/gallery': {
      id: '/_protected/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof ProtectedGalleryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/example': {
      id: '/_protected/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ProtectedExampleRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat': {
      id: '/_protected/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ProtectedChatRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_guest/signin': {
      id: '/_guest/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof GuestSigninRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedProfileRoute
    }
    '/api/task/submit': {
      id: '/api/task/submit'
      path: '/api/task/submit'
      fullPath: '/api/task/submit'
      preLoaderRoute: typeof ApiTaskSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/task/status': {
      id: '/api/task/status'
      path: '/api/task/status'
      fullPath: '/api/task/status'
      preLoaderRoute: typeof ApiTaskStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/task/cancel': {
      id: '/api/task/cancel'
      path: '/api/task/cancel'
      fullPath: '/api/task/cancel'
      preLoaderRoute: typeof ApiTaskCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models/aihubmix': {
      id: '/api/models/aihubmix'
      path: '/api/models/aihubmix'
      fullPath: '/api/models/aihubmix'
      preLoaderRoute: typeof ApiModelsAihubmixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile/my-projects': {
      id: '/_protected/profile/my-projects'
      path: '/my-projects'
      fullPath: '/profile/my-projects'
      preLoaderRoute: typeof ProtectedProfileMyProjectsRouteImport
      parentRoute: typeof ProtectedProfileRoute
    }
    '/_protected/profile/favorites-projects': {
      id: '/_protected/profile/favorites-projects'
      path: '/favorites-projects'
      fullPath: '/profile/favorites-projects'
      preLoaderRoute: typeof ProtectedProfileFavoritesProjectsRouteImport
      parentRoute: typeof ProtectedProfileRoute
    }
    '/_protected/profile/api-keys': {
      id: '/_protected/profile/api-keys'
      path: '/api-keys'
      fullPath: '/profile/api-keys'
      preLoaderRoute: typeof ProtectedProfileApiKeysRouteImport
      parentRoute: typeof ProtectedProfileRoute
    }
  }
}

interface GuestRouteChildren {
  GuestSigninRoute: typeof GuestSigninRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestSigninRoute: GuestSigninRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface ProtectedProfileRouteChildren {
  ProtectedProfileApiKeysRoute: typeof ProtectedProfileApiKeysRoute
  ProtectedProfileFavoritesProjectsRoute: typeof ProtectedProfileFavoritesProjectsRoute
  ProtectedProfileMyProjectsRoute: typeof ProtectedProfileMyProjectsRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
}

const ProtectedProfileRouteChildren: ProtectedProfileRouteChildren = {
  ProtectedProfileApiKeysRoute: ProtectedProfileApiKeysRoute,
  ProtectedProfileFavoritesProjectsRoute:
    ProtectedProfileFavoritesProjectsRoute,
  ProtectedProfileMyProjectsRoute: ProtectedProfileMyProjectsRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
}

const ProtectedProfileRouteWithChildren =
  ProtectedProfileRoute._addFileChildren(ProtectedProfileRouteChildren)

interface ProtectedRouteChildren {
  ProtectedChatRoute: typeof ProtectedChatRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedExampleRoute: typeof ProtectedExampleRoute
  ProtectedGalleryRoute: typeof ProtectedGalleryRoute
  ProtectedPreviewRoute: typeof ProtectedPreviewRoute
  ProtectedProfileRoute: typeof ProtectedProfileRouteWithChildren
  ProtectedSignoutRoute: typeof ProtectedSignoutRoute
  ProtectedWizardRoute: typeof ProtectedWizardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedChatRoute: ProtectedChatRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedExampleRoute: ProtectedExampleRoute,
  ProtectedGalleryRoute: ProtectedGalleryRoute,
  ProtectedPreviewRoute: ProtectedPreviewRoute,
  ProtectedProfileRoute: ProtectedProfileRouteWithChildren,
  ProtectedSignoutRoute: ProtectedSignoutRoute,
  ProtectedWizardRoute: ProtectedWizardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GuestRoute: GuestRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiMetadataRoute: ApiMetadataRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  ApiModelsAihubmixRoute: ApiModelsAihubmixRoute,
  ApiTaskCancelRoute: ApiTaskCancelRoute,
  ApiTaskStatusRoute: ApiTaskStatusRoute,
  ApiTaskSubmitRoute: ApiTaskSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
